### ISSUE TITLE
Add detailed docstring

### ISSUE THREAD

**Issue by AntoinePassemiers** [janursa/geneRNI#21]
I am currently writing unit tests and fixing design issues, but to go any further I need to know precisely what is the exact format for `KO`, `perturbations` and `time_points`. Could you please add some detailed information about them?

https://github.com/janursa/geneRNI/blob/e3904a0e60f5aa2d8dca519607fad892863f909c/geneRNI/data.py#L10

**Comment by janursa** [comment]
i added the type hints and a short annotation in Data __init__

**Comment by AntoinePassemiers** [comment]
The type hints are not sufficient to make me properly understand the format (also, the type hints are incorrect).

- There seems to be as many samples in dynamic data as there are time points. So then why do we have a double list instead of a simple list?
- What do the perturbations represent? Do the values in `perturbations` represent gene expression after perturbation?
- You wrote `KO` is of size `n_gene`. If this list is as long as the number of genes, what are its elements?

**Comment by janursa** [comment]
- Re "There seems to be as many samples in dynamic data as there are time points. So then why do we have a double list instead of a simple list?": seems like perturbation can happen during the experiment, meaning that it's not always at day 0. Therefore, a list in list is needed to contain time dependent perturbation data.  
- Re "What do the perturbations represent? Do the values in perturbations represent gene expression after perturbation?": i have taken this directly from dynGENIE3, which we either have to change it or cite it. Anyways, 'perturbations' are the protein concentrations added to the experiment. That's why we discount them from the data. 
- Re "You wrote KO is of size n_gene. If this list is as long as the number of genes, what are its elements?": my bad, it's not as long as the number of genes. It is a list that contains the names of KO genes.

**Comment by AntoinePassemiers** [comment]
Regarding the first point, I think I need an example. So if `ss_data` is of shape (n_samples, n_genes) = (7, 30) for example, then `time_points` could be something like [[0, 0.1, 0.3], [0, 0.22, 0.3, 0.45, 0.7]] ? The total number of time points should be equal to the number of samples no? But from the code I see that `len(time_points) == len(ss_data)`. What am I missing here?

**Comment by janursa** [comment]
there is no time_points for ss_data as it's static.  where is `len(time_points) == len(ss_data)`?

**Comment by AntoinePassemiers** [comment]
My mistake, I meant `ts_data`

**Comment by janursa** [comment]
i see. Re "The total number of time points should be equal to the number of samples no? But from the code I see that len(time_points) == len(ss_data). What am I missing here?": 
`time_points` are given in this format [n_experiment*n_time]. In your example, [[0, 0.1, 0.3], [0, 0.22, 0.45, 0.7]], it means that we have 2 experiments with different measurement times of [0, 0.1, 0.3] and [0, 0.22, 0.45, 0.7]. `ts_data` has the same style. For experiment, the measurements are given in the corresponding times. Therefore, `len(time_points) == len(ss_data)` is correct.
The total sample count is the sum of the data coming from all experiments, `n_sample = sum([len(item) for item in ts_data])`. Of note, this is the number of samples before applying the decay_coeff. But, one we applied the coeffs, one sample is reduced at each item of the ts_data `n_sample = sum([len(item)-1 for item in ts_data])`

**Comment by AntoinePassemiers** [comment]
Ok thanks a lot, this makes perfect sense now. So far I was treating `ts_data` as a matrix, not as nested list. I'll change this to a list of arrays.

**Comment by AntoinePassemiers** [comment]
I'm still confused by `KO`. If gene j has been knocked out from experiment/sample i let's say, how do we encode this? Gene j will be listed in `KO`, but how do we know this is only true for sample i?

**Comment by janursa** [comment]
right point. it needs to be nested list. i have taken this directly from dynGENIE3. maybe you can start a new issue on this?
